--[[

Example ported from oficial examples in raylib

source: https://github.com/raysan5/raylib/blob/master/examples/textures/textures_raw_data.c

]]

--[[
	raylib [textures] example - raw data

	Example complexity rating: [★★★☆] 3/4

	Example licensed under an unmodified zlib/libpng license, which is an OSI-certified,
	BSD-like license that allows static linking with closed source software

	Copyright (c) 2015-2025 Ramon Santamaria (@raysan5)
]]

-- Initialization
local screenWidth = 800
local screenHeight = 450

rl.InitWindow(screenWidth, screenHeight, "raylib [textures] example - raw data")

-- Load RAW image data (384x512, 32bit RGBA, no file header)
local fudesumiRaw = rl.LoadImageRaw("resources/fudesumi.raw", 384, 512, rl.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8, 0)
local fudesumi = rl.LoadTextureFromImage(fudesumiRaw)
rl.UnloadImage(fudesumiRaw)

-- Generate a checked texture by code
local imWidth = 960
local imHeight = 480

-- Create pixel data as a Color array
local pixels = rl.new("Color[?]", imWidth * imHeight)

for y = 0, imHeight - 1 do
	for x = 0, imWidth - 1 do
		if math.floor(x / 32 + y / 32) % 2 == 0 then
			pixels[y * imWidth + x] = rl.ORANGE
		else
			pixels[y * imWidth + x] = rl.GOLD
		end
	end
end

-- Create image from raw pixel data
local checkedIm = rl.new("Image")
checkedIm.data = pixels
checkedIm.width = imWidth
checkedIm.height = imHeight
checkedIm.format = rl.PIXELFORMAT_UNCOMPRESSED_R8G8B8A8
checkedIm.mipmaps = 1

local checked = rl.LoadTextureFromImage(checkedIm)
rl.UnloadImage(checkedIm)

rl.SetTargetFPS(60)

-- Main game loop
while not rl.WindowShouldClose() do
	rl.BeginDrawing()

	rl.ClearBackground(rl.RAYWHITE)

	rl.DrawTexture(checked, math.floor(screenWidth / 2 - checked.width / 2), math.floor(screenHeight / 2 - checked.height / 2), rl.Fade(rl.WHITE, 0.5))
	rl.DrawTexture(fudesumi, 430, -30, rl.WHITE)

	rl.DrawText("CHECKED TEXTURE ", 84, 85, 30, rl.BROWN)
	rl.DrawText("GENERATED by CODE", 72, 148, 30, rl.BROWN)
	rl.DrawText("and RAW IMAGE LOADING", 46, 210, 30, rl.BROWN)

	rl.DrawText("(c) Fudesumi sprite by Eiden Marsal", 310, screenHeight - 20, 10, rl.BROWN)

	rl.EndDrawing()
end

-- De-Initialization
rl.UnloadTexture(fudesumi)
rl.UnloadTexture(checked)

rl.CloseWindow()
