typedef void (*AudioCallback)(void *bufferData, unsigned int frames)
typedef unsigned char *(*LoadFileDataCallback)(const char *fileName, int *dataSize)
typedef char *(*LoadFileTextCallback)(const char *fileName)
typedef bool (*SaveFileDataCallback)(const char *fileName, void *data, int dataSize)
typedef bool (*SaveFileTextCallback)(const char *fileName, const char *text)
void AttachAudioMixedProcessor(AudioCallback processor)
void AttachAudioStreamProcessor(AudioStream stream, AudioCallback processor)
void BeginBlendMode(int mode)
void BeginDrawing(void)
void BeginMode2D(Camera2D camera)
void BeginMode3D(Camera3D camera)
void BeginScissorMode(int x, int y, int width, int height)
void BeginShaderMode(Shader shader)
void BeginTextureMode(RenderTexture2D target)
void BeginVrStereoMode(VrStereoConfig config)
bool ChangeDirectory(const char *dirPath)
bool CheckCollisionBoxSphere(BoundingBox box, Vector3 center, float radius)
bool CheckCollisionBoxes(BoundingBox box1, BoundingBox box2)
bool CheckCollisionCircleLine(Vector2 center, float radius, Vector2 p1, Vector2 p2)
bool CheckCollisionCircleRec(Vector2 center, float radius, Rectangle rec)
bool CheckCollisionCircles(Vector2 center1, float radius1, Vector2 center2, float radius2)
bool CheckCollisionLines(Vector2 startPos1, Vector2 endPos1, Vector2 startPos2, Vector2 endPos2, Vector2 *collisionPoint)
bool CheckCollisionPointCircle(Vector2 point, Vector2 center, float radius)
bool CheckCollisionPointLine(Vector2 point, Vector2 p1, Vector2 p2, int threshold)
bool CheckCollisionPointPoly(Vector2 point, const Vector2 *points, int pointCount)
bool CheckCollisionPointRec(Vector2 point, Rectangle rec)
bool CheckCollisionPointTriangle(Vector2 point, Vector2 p1, Vector2 p2, Vector2 p3)
bool CheckCollisionRecs(Rectangle rec1, Rectangle rec2)
bool CheckCollisionSpheres(Vector3 center1, float radius1, Vector3 center2, float radius2)
void ClearBackground(Color color)
void ClearWindowState(unsigned int flags)
void CloseAudioDevice(void)
void CloseWindow(void)
const char *CodepointToUTF8(int codepoint, int *utf8Size)
Color ColorAlpha(Color color, float alpha)
Color ColorAlphaBlend(Color dst, Color src, Color tint)
Color ColorBrightness(Color color, float factor)
Color ColorContrast(Color color, float contrast)
Color ColorFromHSV(float hue, float saturation, float value)
Color ColorFromNormalized(Vector4 normalized)
bool ColorIsEqual(Color col1, Color col2)
Color ColorLerp(Color color1, Color color2, float factor)
Vector4 ColorNormalize(Color color)
Color ColorTint(Color color, Color tint)
Vector3 ColorToHSV(Color color)
int ColorToInt(Color color)
unsigned char *CompressData(const unsigned char *data, int dataSize, int *compDataSize)
unsigned int ComputeCRC32(unsigned char *data, int dataSize)
unsigned int *ComputeMD5(unsigned char *data, int dataSize)
unsigned int *ComputeSHA1(unsigned char *data, int dataSize)
unsigned int *ComputeSHA256(unsigned char *data, int dataSize)
unsigned char *DecodeDataBase64(const char *text, int *outputSize)
unsigned char *DecompressData(const unsigned char *compData, int compDataSize, int *dataSize)
void DetachAudioMixedProcessor(AudioCallback processor)
void DetachAudioStreamProcessor(AudioStream stream, AudioCallback processor)
bool DirectoryExists(const char *dirPath)
void DisableCursor(void)
void DisableEventWaiting(void)
void DrawBillboard(Camera camera, Texture2D texture, Vector3 position, float scale, Color tint)
void DrawBillboardPro(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector3 up, Vector2 size, Vector2 origin, float rotation, Color tint)
void DrawBillboardRec(Camera camera, Texture2D texture, Rectangle source, Vector3 position, Vector2 size, Color tint)
void DrawBoundingBox(BoundingBox box, Color color)
void DrawCapsule(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color)
void DrawCapsuleWires(Vector3 startPos, Vector3 endPos, float radius, int slices, int rings, Color color)
void DrawCircle(int centerX, int centerY, float radius, Color color)
void DrawCircle3D(Vector3 center, float radius, Vector3 rotationAxis, float rotationAngle, Color color)
void DrawCircleGradient(Vector2 center, float radius, Color inner, Color outer)
void DrawCircleLines(int centerX, int centerY, float radius, Color color)
void DrawCircleLinesV(Vector2 center, float radius, Color color)
void DrawCircleSector(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color)
void DrawCircleSectorLines(Vector2 center, float radius, float startAngle, float endAngle, int segments, Color color)
void DrawCircleV(Vector2 center, float radius, Color color)
void DrawCube(Vector3 position, float width, float height, float length, Color color)
void DrawCubeV(Vector3 position, Vector3 size, Color color)
void DrawCubeWires(Vector3 position, float width, float height, float length, Color color)
void DrawCubeWiresV(Vector3 position, Vector3 size, Color color)
void DrawCylinder(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color)
void DrawCylinderEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color)
void DrawCylinderWires(Vector3 position, float radiusTop, float radiusBottom, float height, int slices, Color color)
void DrawCylinderWiresEx(Vector3 startPos, Vector3 endPos, float startRadius, float endRadius, int sides, Color color)
void DrawEllipse(int centerX, int centerY, float radiusH, float radiusV, Color color)
void DrawEllipseLines(int centerX, int centerY, float radiusH, float radiusV, Color color)
void DrawEllipseLinesV(Vector2 center, float radiusH, float radiusV, Color color)
void DrawEllipseV(Vector2 center, float radiusH, float radiusV, Color color)
void DrawFPS(int posX, int posY)
void DrawGrid(int slices, float spacing)
void DrawLine(int startPosX, int startPosY, int endPosX, int endPosY, Color color)
void DrawLine3D(Vector3 startPos, Vector3 endPos, Color color)
void DrawLineBezier(Vector2 startPos, Vector2 endPos, float thick, Color color)
void DrawLineDashed(Vector2 startPos, Vector2 endPos, int dashSize, int spaceSize, Color color)
void DrawLineEx(Vector2 startPos, Vector2 endPos, float thick, Color color)
void DrawLineStrip(const Vector2 *points, int pointCount, Color color)
void DrawLineV(Vector2 startPos, Vector2 endPos, Color color)
void DrawMesh(Mesh mesh, Material material, Matrix transform)
void DrawMeshInstanced(Mesh mesh, Material material, const Matrix *transforms, int instances)
void DrawModel(Model model, Vector3 position, float scale, Color tint)
void DrawModelEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint)
void DrawModelWires(Model model, Vector3 position, float scale, Color tint)
void DrawModelWiresEx(Model model, Vector3 position, Vector3 rotationAxis, float rotationAngle, Vector3 scale, Color tint)
void DrawPixel(int posX, int posY, Color color)
void DrawPixelV(Vector2 position, Color color)
void DrawPlane(Vector3 centerPos, Vector2 size, Color color)
void DrawPoint3D(Vector3 position, Color color)
void DrawPoly(Vector2 center, int sides, float radius, float rotation, Color color)
void DrawPolyLines(Vector2 center, int sides, float radius, float rotation, Color color)
void DrawPolyLinesEx(Vector2 center, int sides, float radius, float rotation, float lineThick, Color color)
void DrawRay(Ray ray, Color color)
void DrawRectangle(int posX, int posY, int width, int height, Color color)
void DrawRectangleGradientEx(Rectangle rec, Color topLeft, Color bottomLeft, Color bottomRight, Color topRight)
void DrawRectangleGradientH(int posX, int posY, int width, int height, Color left, Color right)
void DrawRectangleGradientV(int posX, int posY, int width, int height, Color top, Color bottom)
void DrawRectangleLines(int posX, int posY, int width, int height, Color color)
void DrawRectangleLinesEx(Rectangle rec, float lineThick, Color color)
void DrawRectanglePro(Rectangle rec, Vector2 origin, float rotation, Color color)
void DrawRectangleRec(Rectangle rec, Color color)
void DrawRectangleRounded(Rectangle rec, float roundness, int segments, Color color)
void DrawRectangleRoundedLines(Rectangle rec, float roundness, int segments, Color color)
void DrawRectangleRoundedLinesEx(Rectangle rec, float roundness, int segments, float lineThick, Color color)
void DrawRectangleV(Vector2 position, Vector2 size, Color color)
void DrawRing(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color)
void DrawRingLines(Vector2 center, float innerRadius, float outerRadius, float startAngle, float endAngle, int segments, Color color)
void DrawSphere(Vector3 centerPos, float radius, Color color)
void DrawSphereEx(Vector3 centerPos, float radius, int rings, int slices, Color color)
void DrawSphereWires(Vector3 centerPos, float radius, int rings, int slices, Color color)
void DrawSplineBasis(const Vector2 *points, int pointCount, float thick, Color color)
void DrawSplineBezierCubic(const Vector2 *points, int pointCount, float thick, Color color)
void DrawSplineBezierQuadratic(const Vector2 *points, int pointCount, float thick, Color color)
void DrawSplineCatmullRom(const Vector2 *points, int pointCount, float thick, Color color)
void DrawSplineLinear(const Vector2 *points, int pointCount, float thick, Color color)
void DrawSplineSegmentBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color)
void DrawSplineSegmentBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float thick, Color color)
void DrawSplineSegmentBezierQuadratic(Vector2 p1, Vector2 c2, Vector2 p3, float thick, Color color)
void DrawSplineSegmentCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float thick, Color color)
void DrawSplineSegmentLinear(Vector2 p1, Vector2 p2, float thick, Color color)
void DrawText(const char *text, int posX, int posY, int fontSize, Color color)
void DrawTextCodepoint(Font font, int codepoint, Vector2 position, float fontSize, Color tint)
void DrawTextCodepoints(Font font, const int *codepoints, int codepointCount, Vector2 position, float fontSize, float spacing, Color tint)
void DrawTextEx(Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint)
void DrawTextPro(Font font, const char *text, Vector2 position, Vector2 origin, float rotation, float fontSize, float spacing, Color tint)
void DrawTexture(Texture2D texture, int posX, int posY, Color tint)
void DrawTextureEx(Texture2D texture, Vector2 position, float rotation, float scale, Color tint)
void DrawTextureNPatch(Texture2D texture, NPatchInfo nPatchInfo, Rectangle dest, Vector2 origin, float rotation, Color tint)
void DrawTexturePro(Texture2D texture, Rectangle source, Rectangle dest, Vector2 origin, float rotation, Color tint)
void DrawTextureRec(Texture2D texture, Rectangle source, Vector2 position, Color tint)
void DrawTextureV(Texture2D texture, Vector2 position, Color tint)
void DrawTriangle(Vector2 v1, Vector2 v2, Vector2 v3, Color color)
void DrawTriangle3D(Vector3 v1, Vector3 v2, Vector3 v3, Color color)
void DrawTriangleFan(const Vector2 *points, int pointCount, Color color)
void DrawTriangleLines(Vector2 v1, Vector2 v2, Vector2 v3, Color color)
void DrawTriangleStrip(const Vector2 *points, int pointCount, Color color)
void DrawTriangleStrip3D(const Vector3 *points, int pointCount, Color color)
void EnableCursor(void)
void EnableEventWaiting(void)
char *EncodeDataBase64(const unsigned char *data, int dataSize, int *outputSize)
void EndBlendMode(void)
void EndDrawing(void)
void EndMode2D(void)
void EndMode3D(void)
void EndScissorMode(void)
void EndShaderMode(void)
void EndTextureMode(void)
void EndVrStereoMode(void)
bool ExportAutomationEventList(AutomationEventList list, const char *fileName)
bool ExportDataAsCode(const unsigned char *data, int dataSize, const char *fileName)
bool ExportFontAsCode(Font font, const char *fileName)
bool ExportImage(Image image, const char *fileName)
bool ExportImageAsCode(Image image, const char *fileName)
unsigned char *ExportImageToMemory(Image image, const char *fileType, int *fileSize)
bool ExportMesh(Mesh mesh, const char *fileName)
bool ExportMeshAsCode(Mesh mesh, const char *fileName)
bool ExportWave(Wave wave, const char *fileName)
bool ExportWaveAsCode(Wave wave, const char *fileName)
Color Fade(Color color, float alpha)
int FileCopy(const char *srcPath, const char *dstPath)
bool FileExists(const char *fileName)
int FileMove(const char *srcPath, const char *dstPath)
int FileRemove(const char *fileName)
int FileRename(const char *fileName, const char *fileRename)
int FileTextFindIndex(const char *fileName, const char *search)
int FileTextReplace(const char *fileName, const char *search, const char *replacement)
Image GenImageCellular(int width, int height, int tileSize)
Image GenImageChecked(int width, int height, int checksX, int checksY, Color col1, Color col2)
Image GenImageColor(int width, int height, Color color)
Image GenImageFontAtlas(const GlyphInfo *glyphs, Rectangle **glyphRecs, int glyphCount, int fontSize, int padding, int packMethod)
Image GenImageGradientLinear(int width, int height, int direction, Color start, Color end)
Image GenImageGradientRadial(int width, int height, float density, Color inner, Color outer)
Image GenImageGradientSquare(int width, int height, float density, Color inner, Color outer)
Image GenImagePerlinNoise(int width, int height, int offsetX, int offsetY, float scale)
Image GenImageText(int width, int height, const char *text)
Image GenImageWhiteNoise(int width, int height, float factor)
Mesh GenMeshCone(float radius, float height, int slices)
Mesh GenMeshCube(float width, float height, float length)
Mesh GenMeshCubicmap(Image cubicmap, Vector3 cubeSize)
Mesh GenMeshCylinder(float radius, float height, int slices)
Mesh GenMeshHeightmap(Image heightmap, Vector3 size)
Mesh GenMeshHemiSphere(float radius, int rings, int slices)
Mesh GenMeshKnot(float radius, float size, int radSeg, int sides)
Mesh GenMeshPlane(float width, float length, int resX, int resZ)
Mesh GenMeshPoly(int sides, float radius)
Mesh GenMeshSphere(float radius, int rings, int slices)
void GenMeshTangents(Mesh *mesh)
Mesh GenMeshTorus(float radius, float size, int radSeg, int sides)
void GenTextureMipmaps(Texture2D *texture)
const char *GetApplicationDirectory(void)
Matrix GetCameraMatrix(Camera camera)
Matrix GetCameraMatrix2D(Camera2D camera)
int GetCharPressed(void)
Image GetClipboardImage(void)
const char *GetClipboardText(void)
int GetCodepoint(const char *text, int *codepointSize)
int GetCodepointCount(const char *text)
int GetCodepointNext(const char *text, int *codepointSize)
int GetCodepointPrevious(const char *text, int *codepointSize)
Rectangle GetCollisionRec(Rectangle rec1, Rectangle rec2)
Color GetColor(unsigned int hexValue)
int GetCurrentMonitor(void)
unsigned int GetDirectoryFileCount(const char *dirPath)
unsigned int GetDirectoryFileCountEx(const char *basePath, const char *filter, bool scanSubdirs)
const char *GetDirectoryPath(const char *filePath)
int GetFPS(void)
const char *GetFileExtension(const char *fileName)
int GetFileLength(const char *fileName)
long GetFileModTime(const char *fileName)
const char *GetFileName(const char *filePath)
const char *GetFileNameWithoutExt(const char *filePath)
Font GetFontDefault(void)
float GetFrameTime(void)
int GetGamepadAxisCount(int gamepad)
float GetGamepadAxisMovement(int gamepad, int axis)
int GetGamepadButtonPressed(void)
const char *GetGamepadName(int gamepad)
int GetGestureDetected(void)
float GetGestureDragAngle(void)
Vector2 GetGestureDragVector(void)
float GetGestureHoldDuration(void)
float GetGesturePinchAngle(void)
Vector2 GetGesturePinchVector(void)
Rectangle GetGlyphAtlasRec(Font font, int codepoint)
int GetGlyphIndex(Font font, int codepoint)
GlyphInfo GetGlyphInfo(Font font, int codepoint)
Rectangle GetImageAlphaBorder(Image image, float threshold)
Color GetImageColor(Image image, int x, int y)
const char *GetKeyName(int key)
int GetKeyPressed(void)
float GetMasterVolume(void)
BoundingBox GetMeshBoundingBox(Mesh mesh)
BoundingBox GetModelBoundingBox(Model model)
int GetMonitorCount(void)
int GetMonitorHeight(int monitor)
const char *GetMonitorName(int monitor)
int GetMonitorPhysicalHeight(int monitor)
int GetMonitorPhysicalWidth(int monitor)
Vector2 GetMonitorPosition(int monitor)
int GetMonitorRefreshRate(int monitor)
int GetMonitorWidth(int monitor)
Vector2 GetMouseDelta(void)
Vector2 GetMousePosition(void)
float GetMouseWheelMove(void)
Vector2 GetMouseWheelMoveV(void)
int GetMouseX(void)
int GetMouseY(void)
float GetMusicTimeLength(Music music)
float GetMusicTimePlayed(Music music)
Color GetPixelColor(void *srcPtr, int format)
int GetPixelDataSize(int width, int height, int format)
const char *GetPrevDirectoryPath(const char *dirPath)
int GetRandomValue(int min, int max)
RayCollision GetRayCollisionBox(Ray ray, BoundingBox box)
RayCollision GetRayCollisionMesh(Ray ray, Mesh mesh, Matrix transform)
RayCollision GetRayCollisionQuad(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3, Vector3 p4)
RayCollision GetRayCollisionSphere(Ray ray, Vector3 center, float radius)
RayCollision GetRayCollisionTriangle(Ray ray, Vector3 p1, Vector3 p2, Vector3 p3)
int GetRenderHeight(void)
int GetRenderWidth(void)
int GetScreenHeight(void)
Vector2 GetScreenToWorld2D(Vector2 position, Camera2D camera)
Ray GetScreenToWorldRay(Vector2 position, Camera camera)
Ray GetScreenToWorldRayEx(Vector2 position, Camera camera, int width, int height)
int GetScreenWidth(void)
int GetShaderLocation(Shader shader, const char *uniformName)
int GetShaderLocationAttrib(Shader shader, const char *attribName)
Texture2D GetShapesTexture(void)
Rectangle GetShapesTextureRectangle(void)
Vector2 GetSplinePointBasis(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t)
Vector2 GetSplinePointBezierCubic(Vector2 p1, Vector2 c2, Vector2 c3, Vector2 p4, float t)
Vector2 GetSplinePointBezierQuad(Vector2 p1, Vector2 c2, Vector2 p3, float t)
Vector2 GetSplinePointCatmullRom(Vector2 p1, Vector2 p2, Vector2 p3, Vector2 p4, float t)
Vector2 GetSplinePointLinear(Vector2 startPos, Vector2 endPos, float t)
char *GetTextBetween(const char *text, const char *begin, const char *end)
double GetTime(void)
int GetTouchPointCount(void)
int GetTouchPointId(int index)
Vector2 GetTouchPosition(int index)
int GetTouchX(void)
int GetTouchY(void)
void *GetWindowHandle(void)
Vector2 GetWindowPosition(void)
Vector2 GetWindowScaleDPI(void)
const char *GetWorkingDirectory(void)
Vector2 GetWorldToScreen(Vector3 position, Camera camera)
Vector2 GetWorldToScreen2D(Vector2 position, Camera2D camera)
Vector2 GetWorldToScreenEx(Vector3 position, Camera camera, int width, int height)
void HideCursor(void)
void ImageAlphaClear(Image *image, Color color, float threshold)
void ImageAlphaCrop(Image *image, float threshold)
void ImageAlphaMask(Image *image, Image alphaMask)
void ImageAlphaPremultiply(Image *image)
void ImageBlurGaussian(Image *image, int blurSize)
void ImageClearBackground(Image *dst, Color color)
void ImageColorBrightness(Image *image, int brightness)
void ImageColorContrast(Image *image, float contrast)
void ImageColorGrayscale(Image *image)
void ImageColorInvert(Image *image)
void ImageColorReplace(Image *image, Color color, Color replace)
void ImageColorTint(Image *image, Color color)
Image ImageCopy(Image image)
void ImageCrop(Image *image, Rectangle crop)
void ImageDither(Image *image, int rBpp, int gBpp, int bBpp, int aBpp)
void ImageDraw(Image *dst, Image src, Rectangle srcRec, Rectangle dstRec, Color tint)
void ImageDrawCircle(Image *dst, int centerX, int centerY, int radius, Color color)
void ImageDrawCircleLines(Image *dst, int centerX, int centerY, int radius, Color color)
void ImageDrawCircleLinesV(Image *dst, Vector2 center, int radius, Color color)
void ImageDrawCircleV(Image *dst, Vector2 center, int radius, Color color)
void ImageDrawLine(Image *dst, int startPosX, int startPosY, int endPosX, int endPosY, Color color)
void ImageDrawLineEx(Image *dst, Vector2 start, Vector2 end, int thick, Color color)
void ImageDrawLineV(Image *dst, Vector2 start, Vector2 end, Color color)
void ImageDrawPixel(Image *dst, int posX, int posY, Color color)
void ImageDrawPixelV(Image *dst, Vector2 position, Color color)
void ImageDrawRectangle(Image *dst, int posX, int posY, int width, int height, Color color)
void ImageDrawRectangleLines(Image *dst, Rectangle rec, int thick, Color color)
void ImageDrawRectangleRec(Image *dst, Rectangle rec, Color color)
void ImageDrawRectangleV(Image *dst, Vector2 position, Vector2 size, Color color)
void ImageDrawText(Image *dst, const char *text, int posX, int posY, int fontSize, Color color)
void ImageDrawTextEx(Image *dst, Font font, const char *text, Vector2 position, float fontSize, float spacing, Color tint)
void ImageDrawTriangle(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color)
void ImageDrawTriangleEx(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color c1, Color c2, Color c3)
void ImageDrawTriangleFan(Image *dst, const Vector2 *points, int pointCount, Color color)
void ImageDrawTriangleLines(Image *dst, Vector2 v1, Vector2 v2, Vector2 v3, Color color)
void ImageDrawTriangleStrip(Image *dst, const Vector2 *points, int pointCount, Color color)
void ImageFlipHorizontal(Image *image)
void ImageFlipVertical(Image *image)
void ImageFormat(Image *image, int newFormat)
Image ImageFromChannel(Image image, int selectedChannel)
Image ImageFromImage(Image image, Rectangle rec)
void ImageKernelConvolution(Image *image, const float *kernel, int kernelSize)
void ImageMipmaps(Image *image)
void ImageResize(Image *image, int newWidth, int newHeight)
void ImageResizeCanvas(Image *image, int newWidth, int newHeight, int offsetX, int offsetY, Color fill)
void ImageResizeNN(Image *image, int newWidth, int newHeight)
void ImageRotate(Image *image, int degrees)
void ImageRotateCCW(Image *image)
void ImageRotateCW(Image *image)
Image ImageText(const char *text, int fontSize, Color color)
Image ImageTextEx(Font font, const char *text, float fontSize, float spacing, Color tint)
void ImageToPOT(Image *image, Color fill)
void InitAudioDevice(void)
void InitWindow(int width, int height, const char *title)
bool IsAudioDeviceReady(void)
bool IsAudioStreamPlaying(AudioStream stream)
bool IsAudioStreamProcessed(AudioStream stream)
bool IsAudioStreamValid(AudioStream stream)
bool IsCursorHidden(void)
bool IsCursorOnScreen(void)
bool IsFileDropped(void)
bool IsFileExtension(const char *fileName, const char *ext)
bool IsFileNameValid(const char *fileName)
bool IsFontValid(Font font)
bool IsGamepadAvailable(int gamepad)
bool IsGamepadButtonDown(int gamepad, int button)
bool IsGamepadButtonPressed(int gamepad, int button)
bool IsGamepadButtonReleased(int gamepad, int button)
bool IsGamepadButtonUp(int gamepad, int button)
bool IsGestureDetected(unsigned int gesture)
bool IsImageValid(Image image)
bool IsKeyDown(int key)
bool IsKeyPressed(int key)
bool IsKeyPressedRepeat(int key)
bool IsKeyReleased(int key)
bool IsKeyUp(int key)
bool IsMaterialValid(Material material)
bool IsModelAnimationValid(Model model, ModelAnimation anim)
bool IsModelValid(Model model)
bool IsMouseButtonDown(int button)
bool IsMouseButtonPressed(int button)
bool IsMouseButtonReleased(int button)
bool IsMouseButtonUp(int button)
bool IsMusicStreamPlaying(Music music)
bool IsMusicValid(Music music)
bool IsPathFile(const char *path)
bool IsRenderTextureValid(RenderTexture2D target)
bool IsShaderValid(Shader shader)
bool IsSoundPlaying(Sound sound)
bool IsSoundValid(Sound sound)
bool IsTextureValid(Texture2D texture)
bool IsWaveValid(Wave wave)
bool IsWindowFocused(void)
bool IsWindowFullscreen(void)
bool IsWindowHidden(void)
bool IsWindowMaximized(void)
bool IsWindowMinimized(void)
bool IsWindowReady(void)
bool IsWindowResized(void)
bool IsWindowState(unsigned int flag)
AudioStream LoadAudioStream(unsigned int sampleRate, unsigned int sampleSize, unsigned int channels)
AutomationEventList LoadAutomationEventList(const char *fileName)
int *LoadCodepoints(const char *text, int *count)
FilePathList LoadDirectoryFiles(const char *dirPath)
FilePathList LoadDirectoryFilesEx(const char *basePath, const char *filter, bool scanSubdirs)
FilePathList LoadDroppedFiles(void)
unsigned char *LoadFileData(const char *fileName, int *dataSize)
char *LoadFileText(const char *fileName)
Font LoadFont(const char *fileName)
GlyphInfo *LoadFontData(const unsigned char *fileData, int dataSize, int fontSize, const int *codepoints, int codepointCount, int type, int *glyphCount)
Font LoadFontEx(const char *fileName, int fontSize, const int *codepoints, int codepointCount)
Font LoadFontFromImage(Image image, Color key, int firstChar)
Font LoadFontFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int fontSize, const int *codepoints, int codepointCount)
Image LoadImage(const char *fileName)
Image LoadImageAnim(const char *fileName, int *frames)
Image LoadImageAnimFromMemory(const char *fileType, const unsigned char *fileData, int dataSize, int *frames)
Color *LoadImageColors(Image image)
Image LoadImageFromMemory(const char *fileType, const unsigned char *fileData, int dataSize)
Image LoadImageFromScreen(void)
Image LoadImageFromTexture(Texture2D texture)
Color *LoadImagePalette(Image image, int maxPaletteSize, int *colorCount)
Image LoadImageRaw(const char *fileName, int width, int height, int format, int headerSize)
Material LoadMaterialDefault(void)
Material *LoadMaterials(const char *fileName, int *materialCount)
Model LoadModel(const char *fileName)
ModelAnimation *LoadModelAnimations(const char *fileName, int *animCount)
Model LoadModelFromMesh(Mesh mesh)
Music LoadMusicStream(const char *fileName)
Music LoadMusicStreamFromMemory(const char *fileType, const unsigned char *data, int dataSize)
int *LoadRandomSequence(unsigned int count, int min, int max)
RenderTexture2D LoadRenderTexture(int width, int height)
Shader LoadShader(const char *vsFileName, const char *fsFileName)
Shader LoadShaderFromMemory(const char *vsCode, const char *fsCode)
Sound LoadSound(const char *fileName)
Sound LoadSoundAlias(Sound source)
Sound LoadSoundFromWave(Wave wave)
char **LoadTextLines(const char *text, int *count)
Texture2D LoadTexture(const char *fileName)
TextureCubemap LoadTextureCubemap(Image image, int layout)
Texture2D LoadTextureFromImage(Image image)
char *LoadUTF8(const int *codepoints, int length)
VrStereoConfig LoadVrStereoConfig(VrDeviceInfo device)
Wave LoadWave(const char *fileName)
Wave LoadWaveFromMemory(const char *fileType, const unsigned char *fileData, int dataSize)
float *LoadWaveSamples(Wave wave)
int MakeDirectory(const char *dirPath)
void MaximizeWindow(void)
int MeasureText(const char *text, int fontSize)
Vector2 MeasureTextCodepoints(Font font, const int *codepoints, int length, float fontSize, float spacing)
Vector2 MeasureTextEx(Font font, const char *text, float fontSize, float spacing)
void *MemAlloc(unsigned int size)
void MemFree(void *ptr)
void *MemRealloc(void *ptr, unsigned int size)
void MinimizeWindow(void)
void OpenURL(const char *url)
void PauseAudioStream(AudioStream stream)
void PauseMusicStream(Music music)
void PauseSound(Sound sound)
void PlayAudioStream(AudioStream stream)
void PlayAutomationEvent(AutomationEvent event)
void PlayMusicStream(Music music)
void PlaySound(Sound sound)
void PollInputEvents(void)
void RestoreWindow(void)
void ResumeAudioStream(AudioStream stream)
void ResumeMusicStream(Music music)
void ResumeSound(Sound sound)
bool SaveFileData(const char *fileName, void *data, int dataSize)
bool SaveFileText(const char *fileName, const char *text)
void SeekMusicStream(Music music, float position)
void SetAudioStreamBufferSizeDefault(int size)
void SetAudioStreamCallback(AudioStream stream, AudioCallback callback)
void SetAudioStreamPan(AudioStream stream, float pan)
void SetAudioStreamPitch(AudioStream stream, float pitch)
void SetAudioStreamVolume(AudioStream stream, float volume)
void SetAutomationEventBaseFrame(int frame)
void SetAutomationEventList(AutomationEventList *list)
void SetClipboardText(const char *text)
void SetConfigFlags(unsigned int flags)
void SetExitKey(int key)
int SetGamepadMappings(const char *mappings)
void SetGamepadVibration(int gamepad, float leftMotor, float rightMotor, float duration)
void SetGesturesEnabled(unsigned int flags)
void SetLoadFileDataCallback(LoadFileDataCallback callback)
void SetLoadFileTextCallback(LoadFileTextCallback callback)
void SetMasterVolume(float volume)
void SetMaterialTexture(Material *material, int mapType, Texture2D texture)
void SetModelMeshMaterial(Model *model, int meshId, int materialId)
void SetMouseCursor(int cursor)
void SetMouseOffset(int offsetX, int offsetY)
void SetMousePosition(int x, int y)
void SetMouseScale(float scaleX, float scaleY)
void SetMusicPan(Music music, float pan)
void SetMusicPitch(Music music, float pitch)
void SetMusicVolume(Music music, float volume)
void SetPixelColor(void *dstPtr, Color color, int format)
void SetRandomSeed(unsigned int seed)
void SetSaveFileDataCallback(SaveFileDataCallback callback)
void SetSaveFileTextCallback(SaveFileTextCallback callback)
void SetShaderValue(Shader shader, int locIndex, const void *value, int uniformType)
void SetShaderValueMatrix(Shader shader, int locIndex, Matrix mat)
void SetShaderValueTexture(Shader shader, int locIndex, Texture2D texture)
void SetShaderValueV(Shader shader, int locIndex, const void *value, int uniformType, int count)
void SetShapesTexture(Texture2D texture, Rectangle source)
void SetSoundPan(Sound sound, float pan)
void SetSoundPitch(Sound sound, float pitch)
void SetSoundVolume(Sound sound, float volume)
void SetTargetFPS(int fps)
void SetTextLineSpacing(int spacing)
void SetTextureFilter(Texture2D texture, int filter)
void SetTextureWrap(Texture2D texture, int wrap)
void SetTraceLogLevel(int logLevel)
void SetWindowFocused(void)
void SetWindowIcon(Image image)
void SetWindowIcons(Image *images, int count)
void SetWindowMaxSize(int width, int height)
void SetWindowMinSize(int width, int height)
void SetWindowMonitor(int monitor)
void SetWindowOpacity(float opacity)
void SetWindowPosition(int x, int y)
void SetWindowSize(int width, int height)
void SetWindowState(unsigned int flags)
void SetWindowTitle(const char *title)
void ShowCursor(void)
void StartAutomationEventRecording(void)
void StopAudioStream(AudioStream stream)
void StopAutomationEventRecording(void)
void StopMusicStream(Music music)
void StopSound(Sound sound)
void SwapScreenBuffer(void)
void TakeScreenshot(const char *fileName)
void TextAppend(char *text, const char *append, int *position)
int TextCopy(char *dst, const char *src)
int TextFindIndex(const char *text, const char *search)
const char *TextFormat(const char *text, ...)
char *TextInsert(const char *text, const char *insert, int position)
char *TextInsertAlloc(const char *text, const char *insert, int position)
bool TextIsEqual(const char *text1, const char *text2)
char *TextJoin(char **textList, int count, const char *delimiter)
unsigned int TextLength(const char *text)
const char *TextRemoveSpaces(const char *text)
char *TextReplace(const char *text, const char *search, const char *replacement)
char *TextReplaceAlloc(const char *text, const char *search, const char *replacement)
char *TextReplaceBetween(const char *text, const char *begin, const char *end, const char *replacement)
char *TextReplaceBetweenAlloc(const char *text, const char *begin, const char *end, const char *replacement)
char **TextSplit(const char *text, char delimiter, int *count)
const char *TextSubtext(const char *text, int position, int length)
char *TextToCamel(const char *text)
float TextToFloat(const char *text)
int TextToInteger(const char *text)
char *TextToLower(const char *text)
char *TextToPascal(const char *text)
char *TextToSnake(const char *text)
char *TextToUpper(const char *text)
void ToggleBorderlessWindowed(void)
void ToggleFullscreen(void)
void TraceLog(int logLevel, const char *text, ...)
void UnloadAudioStream(AudioStream stream)
void UnloadAutomationEventList(AutomationEventList list)
void UnloadCodepoints(int *codepoints)
void UnloadDirectoryFiles(FilePathList files)
void UnloadDroppedFiles(FilePathList files)
void UnloadFileData(unsigned char *data)
void UnloadFileText(char *text)
void UnloadFont(Font font)
void UnloadFontData(GlyphInfo *glyphs, int glyphCount)
void UnloadImage(Image image)
void UnloadImageColors(Color *colors)
void UnloadImagePalette(Color *colors)
void UnloadMaterial(Material material)
void UnloadMesh(Mesh mesh)
void UnloadModel(Model model)
void UnloadModelAnimations(ModelAnimation *animations, int animCount)
void UnloadMusicStream(Music music)
void UnloadRandomSequence(int *sequence)
void UnloadRenderTexture(RenderTexture2D target)
void UnloadShader(Shader shader)
void UnloadSound(Sound sound)
void UnloadSoundAlias(Sound alias)
void UnloadTextLines(char **text, int lineCount)
void UnloadTexture(Texture2D texture)
void UnloadUTF8(char *text)
void UnloadVrStereoConfig(VrStereoConfig config)
void UnloadWave(Wave wave)
void UnloadWaveSamples(float *samples)
void UpdateAudioStream(AudioStream stream, const void *data, int frameCount)
void UpdateCamera(Camera *camera, int mode)
void UpdateCameraPro(Camera *camera, Vector3 movement, Vector3 rotation, float zoom)
void UpdateMeshBuffer(Mesh mesh, int index, const void *data, int dataSize, int offset)
void UpdateModelAnimation(Model model, ModelAnimation anim, float frame)
void UpdateModelAnimationEx(Model model, ModelAnimation animA, float frameA, ModelAnimation animB, float frameB, float blend)
void UpdateMusicStream(Music music)
void UpdateSound(Sound sound, const void *data, int sampleCount)
void UpdateTexture(Texture2D texture, const void *pixels)
void UpdateTextureRec(Texture2D texture, Rectangle rec, const void *pixels)
void UploadMesh(Mesh *mesh, bool dynamic)
void WaitTime(double seconds)
Wave WaveCopy(Wave wave)
void WaveCrop(Wave *wave, int initFrame, int finalFrame)
void WaveFormat(Wave *wave, int sampleRate, int sampleSize, int channels)
bool WindowShouldClose(void)
