--[[
  Extracts raylib/raygui/rlgl/physac enum constants from src/raylib.lua's
  ffi.cdef blocks (the only place they're defined) and emits a plain Lua
  file assigning them onto `rl`, for use by the web (non-FFI) build.

  Usage: lua genconst_web.lua <output.lua> <input.lua> [<input.lua> ...]
]]

local out_path = assert(arg[1], "usage: genconst_web.lua <output.lua> <input.lua...>")
assert(arg[2], "usage: genconst_web.lua <output.lua> <input.lua...>")

local values = {}   -- name -> numeric value, in encounter order
local order = {}

local function define(name, value)
  if values[name] == nil then
    order[#order + 1] = name
  end
  values[name] = value
end

for i = 2, #arg do
  local path = arg[i]
  local f = assert(io.open(path, "r"))
  local text = f:read("a")
  f:close()

  -- Walk ffi.cdef [[ ... ]] blocks only.
  for body in text:gmatch("ffi%.cdef%s*%[%[(.-)%]%]") do
    -- Walk typedef enum { ... } Name; blocks within each cdef body.
    for enum_body in body:gmatch("typedef%s+enum[^{]*{(.-)}[^;]*;") do
      local next_value = 0
      for entry in (enum_body .. ","):gmatch("(.-),") do
        entry = entry:gsub("/%*.-%*/", ""):gsub("//[^\n]*", "")
        entry = entry:match("^%s*(.-)%s*$")
        if entry ~= "" then
          local name, expr = entry:match("^([%a_][%w_]*)%s*=%s*(.-)$")
          if name then
            local chunk = load("return (" .. expr .. ")")
            local ok, val = pcall(chunk)
            if ok and type(val) == "number" then
              define(name, val)
              next_value = val + 1
            else
              io.stderr:write(string.format("WARN: could not evaluate %s = %s\n", name, expr))
            end
          else
            name = entry:match("^([%a_][%w_]*)$")
            if name then
              define(name, next_value)
              next_value = next_value + 1
            end
          end
        end
      end
    end
  end

  -- Plain top-level `rl.NAME = <int-literal>` assignments (rlgl GL defines).
  for name, expr in text:gmatch("\nrl%.([%a_][%w_]*)%s*=%s*(0[xX]%x+)%s*\n") do
    define(name, tonumber(expr))
  end
  for name, expr in text:gmatch("\nrl%.([%a_][%w_]*)%s*=%s*(%d+)%s*\n") do
    if values[name] == nil then
      define(name, tonumber(expr))
    end
  end

  -- `rl.NAME = C.OTHER` aliases (resolved against already-collected constants).
  for name, other in text:gmatch("\nrl%.([%a_][%w_]*)%s*=%s*C%.([%a_][%w_]*)%s*\n") do
    if values[other] ~= nil then
      define(name, values[other])
    else
      io.stderr:write(string.format("WARN: alias %s = C.%s : unknown source constant\n", name, other))
    end
  end
end

local out = assert(io.open(out_path, "wb"))
out:write("-- Auto-generated by tools/genconst_web.lua. Do not edit by hand.\n")
for _, name in ipairs(order) do
  out:write(string.format("rl.%s = %d\n", name, values[name]))
end
out:close()

io.stderr:write(string.format("genconst_web: wrote %d constants to %s\n", #order, out_path))
