int GetGestureDetected(void)
float GetGestureDragAngle(void)
Vector2 GetGestureDragVector(void)
float GetGestureHoldDuration(void)
float GetGesturePinchAngle(void)
Vector2 GetGesturePinchVector(void)
bool IsGestureDetected(int gesture)
void ProcessGestureEvent(GestureEvent event)
void SetGesturesEnabled(unsigned int flags)
void UpdateGestures(void)
