void ClosePhysics(void)
PhysicsBody CreatePhysicsBodyCircle(Vector2 pos, float radius, float density)
PhysicsBody CreatePhysicsBodyPolygon(Vector2 pos, float radius, int sides, float density)
PhysicsBody CreatePhysicsBodyRectangle(Vector2 pos, float width, float height, float density)
void DestroyPhysicsBody(PhysicsBody body)
int GetPhysicsBodiesCount(void)
PhysicsBody GetPhysicsBody(int index)
int GetPhysicsShapeType(int index)
Vector2 GetPhysicsShapeVertex(PhysicsBody body, int vertex)
int GetPhysicsShapeVerticesCount(int index)
void InitPhysics(void)
void PhysicsAddForce(PhysicsBody body, Vector2 force)
void PhysicsAddTorque(PhysicsBody body, float amount)
void PhysicsShatter(PhysicsBody body, Vector2 position, float force)
void ResetPhysics(void)
void SetPhysicsBodyRotation(PhysicsBody body, float radians)
void SetPhysicsGravity(float x, float y)
void SetPhysicsTimeStep(double delta)
void UpdatePhysics(void)
