int GuiButton(Rectangle bounds, const char *text)
int GuiCheckBox(Rectangle bounds, const char *text, bool *checked)
int GuiColorBarAlpha(Rectangle bounds, const char *text, float *alpha)
int GuiColorBarHue(Rectangle bounds, const char *text, float *value)
int GuiColorPanel(Rectangle bounds, const char *text, Color *color)
int GuiColorPanelHSV(Rectangle bounds, const char *text, Vector3 *colorHsv)
int GuiColorPicker(Rectangle bounds, const char *text, Color *color)
int GuiColorPickerHSV(Rectangle bounds, const char *text, Vector3 *colorHsv)
int GuiComboBox(Rectangle bounds, const char *text, int *active)
void GuiDisable(void)
void GuiDisableTooltip(void)
void GuiDrawIcon(int iconId, int posX, int posY, int pixelSize, Color color)
int GuiDropdownBox(Rectangle bounds, const char *text, int *active, bool editMode)
int GuiDummyRec(Rectangle bounds, const char *text)
void GuiEnable(void)
void GuiEnableTooltip(void)
Font GuiGetFont(void)
unsigned int *GuiGetIcons(void)
int GuiGetState(void)
int GuiGetStyle(int control, int property)
int GuiGetTextWidth(const char *text)
int GuiGrid(Rectangle bounds, const char *text, float spacing, int subdivs, Vector2 *mouseCell)
int GuiGroupBox(Rectangle bounds, const char *text)
const char *GuiIconText(int iconId, const char *text)
bool GuiIsLocked(void)
int GuiLabel(Rectangle bounds, const char *text)
int GuiLabelButton(Rectangle bounds, const char *text)
int GuiLine(Rectangle bounds, const char *text)
int GuiListView(Rectangle bounds, const char *text, int *scrollIndex, int *active)
int GuiListViewEx(Rectangle bounds, char **text, int count, int *scrollIndex, int *active, int *focus)
char **GuiLoadIcons(const char *fileName, bool loadIconsName)
void GuiLoadStyle(const char *fileName)
void GuiLoadStyleDefault(void)
void GuiLock(void)
int GuiMessageBox(Rectangle bounds, const char *title, const char *message, const char *buttons)
int GuiPanel(Rectangle bounds, const char *text)
int GuiProgressBar(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiScrollPanel(Rectangle bounds, const char *text, Rectangle content, Vector2 *scroll, Rectangle *view)
void GuiSetAlpha(float alpha)
void GuiSetFont(Font font)
void GuiSetIconScale(int scale)
void GuiSetState(int state)
void GuiSetStyle(int control, int property, int value)
void GuiSetTooltip(const char *tooltip)
int GuiSlider(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiSliderBar(Rectangle bounds, const char *textLeft, const char *textRight, float *value, float minValue, float maxValue)
int GuiSpinner(Rectangle bounds, const char *text, int *value, int minValue, int maxValue, bool editMode)
int GuiStatusBar(Rectangle bounds, const char *text)
int GuiTabBar(Rectangle bounds, char **text, int count, int *active)
int GuiTextBox(Rectangle bounds, char *text, int textSize, bool editMode)
int GuiTextInputBox(Rectangle bounds, const char *title, const char *message, const char *buttons, char *text, int textMaxSize, bool *secretViewActive)
int GuiToggle(Rectangle bounds, const char *text, bool *active)
int GuiToggleGroup(Rectangle bounds, const char *text, int *active)
int GuiToggleSlider(Rectangle bounds, const char *text, int *active)
void GuiUnlock(void)
int GuiValueBox(Rectangle bounds, const char *text, int *value, int minValue, int maxValue, bool editMode)
int GuiValueBoxFloat(Rectangle bounds, const char *text, char *textValue, float *value, bool editMode)
int GuiWindowBox(Rectangle bounds, const char *title)
