void CameraMoveForward(Camera *camera, float distance, bool moveInWorldPlane)
void CameraMoveRight(Camera *camera, float distance, bool moveInWorldPlane)
void CameraMoveToTarget(Camera *camera, float delta)
void CameraMoveUp(Camera *camera, float distance)
void CameraPitch(Camera *camera, float angle, bool lockView, bool rotateAroundTarget, bool rotateUp)
void CameraRoll(Camera *camera, float angle)
void CameraYaw(Camera *camera, float angle, bool rotateAroundTarget)
Vector3 GetCameraForward(Camera *camera)
Matrix GetCameraProjectionMatrix(Camera *camera, float aspect)
Vector3 GetCameraRight(Camera *camera)
Vector3 GetCameraUp(Camera *camera)
Matrix GetCameraViewMatrix(Camera *camera)
