void rlActiveDrawBuffers(int count)
void rlActiveTextureSlot(int slot)
void rlBegin(int mode)
void rlBindFramebuffer(unsigned int target, unsigned int framebuffer)
void rlBindImageTexture(unsigned int id, unsigned int index, int format, bool readonly)
void rlBindShaderBuffer(unsigned int id, unsigned int index)
void rlBlitFramebuffer(int srcX, int srcY, int srcWidth, int srcHeight, int dstX, int dstY, int dstWidth, int dstHeight, int bufferMask)
void rlCheckErrors(void)
bool rlCheckRenderBatchLimit(int vCount)
void rlClearColor(unsigned char r, unsigned char g, unsigned char b, unsigned char a)
void rlClearScreenBuffers(void)
void rlColor3f(float x, float y, float z)
void rlColor4f(float x, float y, float z, float w)
void rlColor4ub(unsigned char r, unsigned char g, unsigned char b, unsigned char a)
void rlColorMask(bool r, bool g, bool b, bool a)
void rlComputeShaderDispatch(unsigned int groupX, unsigned int groupY, unsigned int groupZ)
void rlCopyFramebuffer(int x, int y, int width, int height, int format, void *pixels)
void rlCopyShaderBuffer(unsigned int destId, unsigned int srcId, unsigned int destOffset, unsigned int srcOffset, unsigned int count)
void rlCubemapParameters(unsigned int id, int param, int value)
void rlDisableBackfaceCulling(void)
void rlDisableColorBlend(void)
void rlDisableDepthMask(void)
void rlDisableDepthTest(void)
void rlDisableFramebuffer(void)
void rlDisablePointMode(void)
void rlDisableScissorTest(void)
void rlDisableShader(void)
void rlDisableSmoothLines(void)
void rlDisableStatePointer(int vertexAttribType)
void rlDisableStereoRender(void)
void rlDisableTexture(void)
void rlDisableTextureCubemap(void)
void rlDisableVertexArray(void)
void rlDisableVertexAttribute(unsigned int index)
void rlDisableVertexBuffer(void)
void rlDisableVertexBufferElement(void)
void rlDisableWireMode(void)
void rlDrawRenderBatch(rlRenderBatch *batch)
void rlDrawRenderBatchActive(void)
void rlDrawVertexArray(int offset, int count)
void rlDrawVertexArrayElements(int offset, int count, const void *buffer)
void rlDrawVertexArrayElementsInstanced(int offset, int count, const void *buffer, int instances)
void rlDrawVertexArrayInstanced(int offset, int count, int instances)
void rlEnableBackfaceCulling(void)
void rlEnableColorBlend(void)
void rlEnableDepthMask(void)
void rlEnableDepthTest(void)
void rlEnableFramebuffer(unsigned int id)
void rlEnablePointMode(void)
void rlEnableScissorTest(void)
void rlEnableShader(unsigned int id)
void rlEnableSmoothLines(void)
void rlEnableStatePointer(int vertexAttribType, void *buffer)
void rlEnableStereoRender(void)
void rlEnableTexture(unsigned int id)
void rlEnableTextureCubemap(unsigned int id)
bool rlEnableVertexArray(unsigned int vaoId)
void rlEnableVertexAttribute(unsigned int index)
void rlEnableVertexBuffer(unsigned int id)
void rlEnableVertexBufferElement(unsigned int id)
void rlEnableWireMode(void)
void rlEnd(void)
void rlFramebufferAttach(unsigned int id, unsigned int texId, int attachType, int texType, int mipLevel)
bool rlFramebufferComplete(unsigned int id)
void rlFrustum(double left, double right, double bottom, double top, double znear, double zfar)
void rlGenTextureMipmaps(unsigned int id, int width, int height, int format, int *mipmaps)
unsigned int rlGetActiveFramebuffer(void)
double rlGetCullDistanceFar(void)
double rlGetCullDistanceNear(void)
int rlGetFramebufferHeight(void)
int rlGetFramebufferWidth(void)
void rlGetGlTextureFormats(int format, unsigned int *glInternalFormat, unsigned int *glFormat, unsigned int *glType)
float rlGetLineWidth(void)
int rlGetLocationAttrib(unsigned int id, const char *attribName)
int rlGetLocationUniform(unsigned int id, const char *uniformName)
Matrix rlGetMatrixModelview(void)
Matrix rlGetMatrixProjection(void)
Matrix rlGetMatrixProjectionStereo(int eye)
Matrix rlGetMatrixTransform(void)
Matrix rlGetMatrixViewOffsetStereo(int eye)
const char *rlGetPixelFormatName(unsigned int format)
float rlGetPointSize(void)
void *rlGetProcAddress(const char *procName)
unsigned int rlGetShaderBufferSize(unsigned int id)
unsigned int rlGetShaderIdDefault(void)
int *rlGetShaderLocsDefault(void)
unsigned int rlGetTextureIdDefault(void)
int rlGetVersion(void)
bool rlIsStereoRenderEnabled(void)
void rlLoadDrawCube(void)
void rlLoadDrawQuad(void)
void rlLoadExtensions(void *loader)
unsigned int rlLoadFramebuffer(void)
void rlLoadIdentity(void)
rlRenderBatch rlLoadRenderBatch(int numBuffers, int bufferElements)
unsigned int rlLoadShader(const char *code, int type)
unsigned int rlLoadShaderBuffer(unsigned int size, const void *data, int usageHint)
unsigned int rlLoadShaderProgram(const char *vsCode, const char *fsCode)
unsigned int rlLoadShaderProgramCompute(unsigned int csId)
unsigned int rlLoadShaderProgramEx(unsigned int vsId, unsigned int fsId)
unsigned int rlLoadTexture(const void *data, int width, int height, int format, int mipmapCount)
unsigned int rlLoadTextureCubemap(const void *data, int size, int format, int mipmapCount)
unsigned int rlLoadTextureDepth(int width, int height, bool useRenderBuffer)
unsigned int rlLoadVertexArray(void)
unsigned int rlLoadVertexBuffer(const void *buffer, int size, bool dynamic)
unsigned int rlLoadVertexBufferElement(const void *buffer, int size, bool dynamic)
void rlMatrixMode(int mode)
void rlMultMatrixf(const float *matf)
void rlNormal3f(float x, float y, float z)
void rlOrtho(double left, double right, double bottom, double top, double znear, double zfar)
void rlPopMatrix(void)
void rlPushMatrix(void)
unsigned char *rlReadScreenPixels(int width, int height)
void rlReadShaderBuffer(unsigned int id, void *dest, unsigned int count, unsigned int offset)
void *rlReadTexturePixels(unsigned int id, int width, int height, int format)
void rlResizeFramebuffer(int width, int height)
void rlRotatef(float angle, float x, float y, float z)
void rlScalef(float x, float y, float z)
void rlScissor(int x, int y, int width, int height)
void rlSetBlendFactors(int glSrcFactor, int glDstFactor, int glEquation)
void rlSetBlendFactorsSeparate(int glSrcRGB, int glDstRGB, int glSrcAlpha, int glDstAlpha, int glEqRGB, int glEqAlpha)
void rlSetBlendMode(int mode)
void rlSetClipPlanes(double nearPlane, double farPlane)
void rlSetCullFace(int mode)
void rlSetFramebufferHeight(int height)
void rlSetFramebufferWidth(int width)
void rlSetLineWidth(float width)
void rlSetMatrixModelview(Matrix view)
void rlSetMatrixProjection(Matrix proj)
void rlSetMatrixProjectionStereo(Matrix right, Matrix left)
void rlSetMatrixViewOffsetStereo(Matrix right, Matrix left)
void rlSetPointSize(float size)
void rlSetRenderBatchActive(rlRenderBatch *batch)
void rlSetShader(unsigned int id, int *locs)
void rlSetTexture(unsigned int id)
void rlSetUniform(int locIndex, const void *value, int uniformType, int count)
void rlSetUniformMatrices(int locIndex, const Matrix *mat, int count)
void rlSetUniformMatrix(int locIndex, Matrix mat)
void rlSetUniformSampler(int locIndex, unsigned int textureId)
void rlSetVertexAttribute(unsigned int index, int compSize, int type, bool normalized, int stride, int offset)
void rlSetVertexAttributeDefault(int locIndex, const void *value, int attribType, int count)
void rlSetVertexAttributeDivisor(unsigned int index, int divisor)
void rlTexCoord2f(float x, float y)
void rlTextureParameters(unsigned int id, int param, int value)
void rlTranslatef(float x, float y, float z)
void rlUnloadFramebuffer(unsigned int id)
void rlUnloadRenderBatch(rlRenderBatch batch)
void rlUnloadShader(unsigned int id)
void rlUnloadShaderBuffer(unsigned int ssboId)
void rlUnloadShaderProgram(unsigned int id)
void rlUnloadTexture(unsigned int id)
void rlUnloadVertexArray(unsigned int vaoId)
void rlUnloadVertexBuffer(unsigned int vboId)
void rlUpdateShaderBuffer(unsigned int id, const void *data, unsigned int dataSize, unsigned int offset)
void rlUpdateTexture(unsigned int id, int offsetX, int offsetY, int width, int height, int format, const void *data)
void rlUpdateVertexBuffer(unsigned int bufferId, const void *data, int dataSize, int offset)
void rlUpdateVertexBufferElements(unsigned int id, const void *data, int dataSize, int offset)
void rlVertex2f(float x, float y)
void rlVertex2i(int x, int y)
void rlVertex3f(float x, float y, float z)
void rlViewport(int x, int y, int width, int height)
void rlglClose(void)
void rlglInit(int width, int height)
